### ISSUE TITLE
GetListValue() should be GetTagValues()

### ISSUE THREAD

**Issue by nicoangelo** [giantswarm/personio-go#12]
First of all, thank you for this library! This finally gave me the perfect excuse to create a Terraform provider for Personio.

While trying to make sense out of the API responses, I did stumble across [this](https://support.personio.de/hc/en-us/articles/208861829-Benutzerdefinierte-Sektionen-und-Attribute-erstellen#attributetypes).  Apparently Personio `list` types are actually just strings, but can be selected from a list of strings (hence the name, I guess). Multi-select lists are called `tags`.

So in principle the implementation of [`GetListValue()`](https://github.com/giantswarm/personio-go/blob/main/v1/personio.go#L123) is correct, but should probably be called `GetTagValues()` and `list` be one of the allowed types in `GetStringValue()`.

Let me know what you think about this - happy to provide a PR.

**Comment by lyind** [comment]
Hi @nicoangelo, sorry for responding late.

Thank you for your suggestion, it absolutely makes sense.

- Do you happen to have an anonymized sample JSON response (to check how such a `"type": "tag"` field looks like)? I wonder if we'd need to trim white-space after splitting on `,`.
- Please provide a PR if you are still interested! 👍

**Comment by nicoangelo** [comment]
Hi @lyind ,

I have an export of all employees of a Personio test instance (Besides my name, everything is autogenerated): https://github.com/nicoangelo/terraform-provider-personio/blob/main/test/data/all_employees.json

In my opinion, "just" splitting is sufficient. I will prepare a PR in the next days with my changes.

**Comment by lyind** [comment]
Thanks for the test data. Yes, just splitting seems alright.

**Comment by lyind** [comment]
Fix released as [#v0.2.0](https://github.com/giantswarm/personio-go/releases/tag/v0.2.0)

Closing.
