### ISSUE TITLE
Unprocessible Entity when providing time offs with a date

### ISSUE THREAD

**Issue by surdaft** [giantswarm/personio-go#3]
https://github.com/giantswarm/personio-go/blob/ffeb4be5cb48d7a10c02bee8acad21d7f353bceb/v1/personio.go#L446

This line outputs the date for the URL in RFC3339 however the API only accepts YYYY-MM-DD format (2006-01-02) otherwise a 422 error is returned.

**Comment by lyind** [comment]
Thank you for this bug report and the proposed fix.

Just some minor polishing and that pro forma form and I will merge it. See PR.

**Comment by lyind** [comment]
The PR resolves this issue, closing.

@surdaft Thank you for your contribution and patience!
