### ISSUE TITLE
Question: Is there an easier way to pull out the department of an employee?

### ISSUE THREAD

**Issue by surdaft** [giantswarm/personio-go#5]
Is there an easier way to pull out the department of an employee? This is what I have right now.. It feels wrong..

```
department := employee.Attributes["department"].Value.(map[string]interface{})["attributes"].(map[string]interface{})["name"]
```

Part of the issue is the complexity of personio's API however I am wondering if you guys know if there is something easier that can be done within the project?

**Comment by lyind** [comment]
Check if this PR serves your needs (see updated readme for how to access `department`): https://github.com/giantswarm/personio-go/pull/6

**Comment by lyind** [comment]
> Part of the issue is the complexity of personio's API

*Complexity* is a nice way to state this. 🤭

**Comment by surdaft** [comment]
@lyind That looks much simpler, thanks for the quick addition and support!
